/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-05-21 14:56:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t    <meta charset=\"UTF-8\">\n");
      out.write("\t    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\t    <title>Login</title>\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("\t    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
      out.write("\t    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\" rel=\"stylesheet\">\n");
      out.write("\t    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">    \n");
      out.write("\t    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t    \t\t<div class=\"head-te\">\n");
      out.write("    \t\t\t\t<h2>Login</h2>\n");
      out.write("\t        ");

	            if(session.getAttribute("customer-delete-status") != null)
	            {
	                if(session.getAttribute("customer-delete-status").toString().equals("success"))
	                    out.println("<font color='blue'> <br><h4>Your account deleted successfully!</h4></font>");
	
	                session.removeAttribute("customer-delete-status");
	            }
	        
      out.write("\n");
      out.write("\t       \t\t</div>\n");
      out.write("\t      \n");
      out.write("\t      <div class=\"main-container\">\n");
      out.write("\t        \t<form action=\"/Cab_It/login\" method=\"POST\">\n");
      out.write("\t\t            \n");
      out.write("\t\t            <label for=\"uname\"><b>Username</b></label>\n");
      out.write("\t\t            <input type=\"text\" name=\"username\" required=\"true\"><br>\n");
      out.write("\t\t            \n");
      out.write("\t\t            <label for=\"psw\"><b>Password</b></label>\n");
      out.write("\t\t            <input type=\"password\" name=\"password\" required=\"true\"><br>\n");
      out.write("\t\t\n");
      out.write("\t\t\t        <input type=\"submit\" value=\"Login\" id=\"login-btn\">\n");
      out.write("\t\t      \n");
      out.write("\t\t            <div class=\"an-btn\">\n");
      out.write("\t\t                <a href=\"/Cab_It/register/customer\"><h4>Don't have an account?</h4></a>\n");
      out.write("\t\t            </div>\n");
      out.write("\t             \n");
      out.write("\t             </form>\n");
      out.write("\t             \n");
      out.write("\t            ");
      out.print(
	       			session.getAttribute("login-status") == "invalid" ? "<h2 id='invalid-btn'>Invalid login!</h2>" : ""
	    		);
      out.write("\n");
      out.write("\t    \t</div>\n");
      out.write("\t    </div>\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
