/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-05-08 09:33:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.validation.employee;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cabit.Cab_It.validation.EmployeeValidation;
import java.io.File;
import java.util.List;
import java.util.Map;
import java.util.Enumeration;

public final class create_002dvalidation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");

        EmployeeValidation employeeValidation = new EmployeeValidation();

        String nic = request.getParameter("nic");
        String username = request.getParameter("username");
        String password = request.getParameter("password");
        String confirmPassword = request.getParameter("confirm-password");
        String firstName = request.getParameter("first-name");
        String midName = request.getParameter("mid-name");
        String lastName = request.getParameter("last-name");
        String addressLine1 = request.getParameter("address-line-1");
        String addressLine2 = request.getParameter("address-line-2");
        String addressLine3 = request.getParameter("address-line-3");
        String city = request.getParameter("city");
        String phone = request.getParameter("phone");
        String bloodGroup = request.getParameter("blood-group");
        String license = request.getParameter("license");
        String location = request.getParameter("location");
        String vehicle = request.getParameter("vehicle");
        String photo = request.getParameter("photo");

        session.setAttribute("prev-nic", nic);
        session.setAttribute("prev-uname", username);
        session.setAttribute("prev-passwd", password);
        session.setAttribute("prev-confirm-passwd", confirmPassword);
        session.setAttribute("prev-fname", firstName);
        session.setAttribute("prev-mname", midName);
        session.setAttribute("prev-lname", lastName);
        session.setAttribute("prev-address-1", addressLine1);
        session.setAttribute("prev-address-2", addressLine2);
        session.setAttribute("prev-address-3", addressLine3);
        session.setAttribute("prev-city", city);
        session.setAttribute("prev-phone", phone);
        session.setAttribute("prev-blood-group", bloodGroup);
        session.setAttribute("prev-license", license);

        Map<String, String> invalidations = employeeValidation.checkFieldInvalidations(
                nic,
                username,
                password,
                confirmPassword,
                firstName,
                lastName,
                addressLine1,
                addressLine2,
                city,
                phone,
                bloodGroup,
                license
        );


        Enumeration<String> sessionAttributes =  session.getAttributeNames();

        while (sessionAttributes.hasMoreElements())
        {
            String element = sessionAttributes.nextElement();

            if(element.endsWith("invalidation"))
                session.removeAttribute(element);
        }

        if(invalidations.isEmpty())
        {
            sessionAttributes = session.getAttributeNames();

            while (sessionAttributes.hasMoreElements())
            {
                String element = sessionAttributes.nextElement();

                if(element.startsWith("prev"))
                    session.removeAttribute(element);
            }

            session.setAttribute("nic", nic);
            session.setAttribute("username", username);
            session.setAttribute("password", password);
            session.setAttribute("first-name", firstName);
            session.setAttribute("mid-name", midName);
            session.setAttribute("last-name", lastName);
            session.setAttribute("address-line-1", addressLine1);
            session.setAttribute("address-line-2", addressLine2);
            session.setAttribute("address-line-3", addressLine3);
            session.setAttribute("city", city);
            session.setAttribute("phone", phone);
            session.setAttribute("blood-group", bloodGroup);
            session.setAttribute("license", license);
            session.setAttribute("location", location);
            session.setAttribute("vehicle", vehicle);
            session.setAttribute("photo", photo);

            session.setAttribute("do-post", 1);

            response.sendRedirect("/Cab_It/register/employee");
        }
        else
        {
            for(String field : invalidations.keySet())
                session.setAttribute(field, invalidations.get(field));

            response.sendRedirect("/Cab_It/employee/create.jsp");
        }
    
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
