/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-05-20 07:24:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Admin Panel</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">    \r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");

        response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

        if(session.getAttribute("logged-admin") == null)
        {
            response.sendRedirect("/Cab_It/login");
            return;
        }
        else if(session.getAttribute("logged-employee") != null)
        {
            session.removeAttribute("logged-employee");
        }
        session.setAttribute("logout-entity", "admin");
    
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"first-row\">\r\n");
      out.write("            <div class=\"main-text\">\r\n");
      out.write("                <h1>Admin Dashboard</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"responsive\">\r\n");
      out.write("                <div class=\"gallery\">\r\n");
      out.write("                  <a  href=\"/Cab_It/logout\">\r\n");
      out.write("                    <i class=\"las la-unlock\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"desc\"><a href=\"/Cab_It/logout\">Click here to logout</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("              <div class=\"responsive\">\r\n");
      out.write("                <div class=\"gallery\">\r\n");
      out.write("                  <a  href=\"/Cab_It/register/employee\">\r\n");
      out.write("                    <i class=\"las la-user-circle\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"desc\"><a href=\"/Cab_It/register/employee\">Click here to employee signup</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("    \r\n");
      out.write("              <div class=\"responsive\">\r\n");
      out.write("                <div class=\"gallery\">\r\n");
      out.write("                  <a  href=\"/Cab_It/fetch/employee\">\r\n");
      out.write("                    <i class=\"las la-eye\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"desc\"><a href=\"/Cab_It/fetch/employee\">Click here to view employee </a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("    \r\n");
      out.write("              <div class=\"responsive\">\r\n");
      out.write("                <div class=\"gallery\">\r\n");
      out.write("                  <a  href=\"/Cab_It/register/vehicle\">\r\n");
      out.write("                    <i class=\"las la-taxi\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"desc\"><a href=\"/Cab_It/register/vehicle\">Click here to register a vehicle </a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"first-row\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"responsive\">\r\n");
      out.write("                <div class=\"gallery\">\r\n");
      out.write("                  <a  href=\"/Cab_It/fetch/vehicle\">\r\n");
      out.write("                    <i class=\"las la-car\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"desc\"><a href=\"/Cab_It/fetch/vehicle\">Click here to view vehicle</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("    \r\n");
      out.write("              <div class=\"responsive\">\r\n");
      out.write("                <div class=\"gallery\">\r\n");
      out.write("                  <a  href=\"/Cab_It/register/location\">\r\n");
      out.write("                    <i class=\"las la-map-marked\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"desc\"><a href=\"/Cab_It/register/location\">Click here to register a location </a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("    \r\n");
      out.write("              <div class=\"responsive\">\r\n");
      out.write("                <div class=\"gallery\">\r\n");
      out.write("                  <a  href=\"/Cab_It/fetch/location\">\r\n");
      out.write("                    <i class=\"las la-map-marked-alt\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"desc\"><a href=\"/Cab_It/fetch/location\">Click here to view location </a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("    \r\n");
      out.write("              <div class=\"responsive\">\r\n");
      out.write("                <div class=\"gallery\">\r\n");
      out.write("                  <a  href=\"/Cab_It/register/advertisement\">\r\n");
      out.write("                    <i class=\"las la-ad\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"desc\"><a href=\"/Cab_It/register/advertisement\">Click here to  register advertisement  </a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"first-row\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"responsive\">\r\n");
      out.write("                <div class=\"gallery\">\r\n");
      out.write("                  <a  href=\"/Cab_It/fetch/advertisement\">\r\n");
      out.write("                    <i class=\"las la-ad\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <div class=\"desc\"><a href=\"/Cab_It/fetch/advertisement\">Click here to view advertisement </a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"last-btn\">\r\n");
      out.write("                <div class=\"responsive\">\r\n");
      out.write("                    <div class=\"gallery\">\r\n");
      out.write("                      <a  href=\"/Cab_It/fetch/order\">\r\n");
      out.write("                        <i class=\"las la-clipboard-list\"></i>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <div class=\"desc\"><a href=\"/Cab_It/fetch/order\">Click here to  view orders </a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>   \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
