/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-05-14 21:51:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vehicle;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cabit.Cab_It.model.Vehicle;
import com.cabit.Cab_It.helper.AccessPrivilegeHelper;
import com.cabit.Cab_It.model.Admin;
import java.util.Enumeration;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t    <meta charset=\"UTF-8\">\r\n");
      out.write("\t    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t    <title>Vehicle Update</title>\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"CSS/style5.css\">\r\n");
      out.write("\t    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("\t    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\t    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">    \r\n");
      out.write("\t    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("    <body>\r\n");
      out.write("        ");

            if(session.getAttribute("logged-admin") == null)
            {
                response.sendRedirect("/Cab_It/login");
                return;
            }
            if(session.getAttribute("update-vehicle") == null)
            {
                response.sendRedirect("/Cab_It/admin/dashboard");
                return;
            }
            AccessPrivilegeHelper accessPrivilegeHelper = new AccessPrivilegeHelper();
            Admin loggedAdmin = (Admin) session.getAttribute("logged-admin");

            if (!accessPrivilegeHelper.checkAccessPrivilegesForVehicle(loggedAdmin, "update")) {
                response.sendRedirect("/Cab_It/error/no-access.jsp");
                return;
            }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

            Vehicle vehicle = (Vehicle) request.getSession().getAttribute("update-vehicle");

            session.setAttribute("vehicle-id", vehicle.getId());
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("        \t<div class=\"head-te\">\r\n");
      out.write("\t            <h2>Vehicle Update</h2>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\t\t<div class=\"main-container\">\r\n");
      out.write("\t\t\t\t<form action=\"/Cab_It/validation/vehicle/update-validation.jsp\" method=\"POST\">\r\n");
      out.write("\t\t            <label for=\" \">Model</label>\r\n");
      out.write("\t\t            <input\r\n");
      out.write("\t\t                    type=\"text\"\r\n");
      out.write("\t\t                    name=\"model\"\r\n");
      out.write("\t\t                    value=");
      out.print( session.getAttribute("prev-model") == null ? vehicle.getModel() : session.getAttribute("prev-model") );
      out.write(">\r\n");
      out.write("\t\t                    <font color=\"red\">\r\n");
      out.write("\t\t                        ");
      out.print( session.getAttribute("model-invalidation") == null ? "" : session.getAttribute("model-invalidation") );
      out.write("\r\n");
      out.write("\t\t                    </font>\r\n");
      out.write("\t\t            <br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t            <label for=\"\">Brand </label>\r\n");
      out.write("\t\t            <input\r\n");
      out.write("\t\t                    type=\"text\"\r\n");
      out.write("\t\t                    name=\"brand\"\r\n");
      out.write("\t\t                    value=");
      out.print( session.getAttribute("prev-brand") == null ? vehicle.getBrand() : session.getAttribute("prev-brand") );
      out.write(">\r\n");
      out.write("\t\t                    <font color=\"red\">\r\n");
      out.write("\t\t                        ");
      out.print( session.getAttribute("brand-invalidation") == null ? "" : session.getAttribute("brand-invalidation") );
      out.write("\r\n");
      out.write("\t\t                    </font>\r\n");
      out.write("\t\t            <br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t           <label for=\"\"> Fuel type </label>\r\n");
      out.write("\t\t            <input\r\n");
      out.write("\t\t                    type=\"text\"\r\n");
      out.write("\t\t                    name=\"fuel-type\"\r\n");
      out.write("\t\t                    value=");
      out.print( session.getAttribute("prev-fuel-type") == null ? vehicle.getFuelType() : session.getAttribute("prev-fuel-type") );
      out.write(">\r\n");
      out.write("\t\t            <br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t            <label for=\"\">Engine type</label> \r\n");
      out.write("\t\t            <input\r\n");
      out.write("\t\t                    type=\"text\"\r\n");
      out.write("\t\t                    name=\"engine-type\"\r\n");
      out.write("\t\t                    value=");
      out.print( session.getAttribute("prev-engine-type") == null ? vehicle.getEngineType() : session.getAttribute("prev-engine-type") );
      out.write(">\r\n");
      out.write("\t\t            <br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t            <label for=\"\">Plate number</label>\r\n");
      out.write("\t\t            <input\r\n");
      out.write("\t\t                    type=\"text\"\r\n");
      out.write("\t\t                    name=\"plate-number\"\r\n");
      out.write("\t\t                    value=");
      out.print( session.getAttribute("prev-plate-number") == null ? vehicle.getPlateNumber() : session.getAttribute("prev-plate-number") );
      out.write(">\r\n");
      out.write("\t\t                    <font color=\"red\">\r\n");
      out.write("\t\t                        ");
      out.print( session.getAttribute("plate-num-invalidation") == null ? "" : session.getAttribute("plate-num-invalidation") );
      out.write("\r\n");
      out.write("\t\t                    </font>\r\n");
      out.write("\t\t            <br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t            <label for=\"\">Top speed</label>\r\n");
      out.write("\t\t            <input\r\n");
      out.write("\t\t                    type=\"text\"\r\n");
      out.write("\t\t                    name=\"top-speed\"\r\n");
      out.write("\t\t                    value=");
      out.print( session.getAttribute("prev-top-speed") == null ? vehicle.getTopSpeed() : session.getAttribute("prev-top-speed") );
      out.write(">\r\n");
      out.write("\t\t                    <font color=\"red\">\r\n");
      out.write("\t\t                        ");
      out.print( session.getAttribute("top-speed-invalidation") == null ? "" : session.getAttribute("top-speed-invalidation") );
      out.write("\r\n");
      out.write("\t\t                    </font>\r\n");
      out.write("\t\t            <br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t           <label for=\"\">Photo </label>\r\n");
      out.write("\t\t            <input\r\n");
      out.write("\t\t                    type=\"file\"\r\n");
      out.write("\t\t                    name=\"photo\"\r\n");
      out.write("\t\t                    value=");
      out.print( session.getAttribute("prev-photo") == null ? "" : session.getAttribute("prev-photo") );
      out.write(">\r\n");
      out.write("\t\t            <br>\r\n");
      out.write("\t\t            <input type=\"submit\" value=\"Update\" id=\"signup-btn\">\r\n");
      out.write("\t        </form>\r\n");
      out.write("\t\r\n");
      out.write("\t        <form action=\"/Cab_It/dashboard\">\r\n");
      out.write("\t            <input type=\"submit\" value=\"Dashboard\" id=\"signup-btn-1\">\r\n");
      out.write("\t        </form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        \r\n");
      out.write("        ");

	    
		   Enumeration<String> sessionAttributes =  session.getAttributeNames();
		
		    while (sessionAttributes.hasMoreElements())
		    {
		        String element = sessionAttributes.nextElement();
		
		        if(element.endsWith("invalidation") || element.startsWith("prev"))
		            session.removeAttribute(element);
		    }
    	
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
